### ISSUE TITLE
Leftover spec?

### ISSUE THREAD

**Issue by onedanshow** [spree-contrib/spree_handling_fees#1]
I assume this is a leftover spec?

https://github.com/mcsweeneys/spree_handling_fees/blob/master/spec/models/handling_charge_spec.rb

There is not a Spree::Calculator::Shipping::HandlingCharge model, so I assume that was part of a first attempt at making a solution before moving to use the normal calculator and the Spree::Adjustment models.

**Comment by brchristian** [comment]
@onedanshow That's exactly right. I'd be happy to see it repurposed into a proper model spec, or discarded in favor of the existing feature spec.
